Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Metrics/LineLength:
  Max: 120

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*_spec.rb"

# Always use double quotes
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Semicolon:
  Exclude:
    - "spec/**/*.rb"

Style/SingleLineMethods:
  Enabled: false
  
Layout/MultilineHashBraceLayout:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"